version: "3.2"
services:

  sql-server-db:
    container_name: node-introduction-db
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - "6400:1433"
    environment:
      SA_PASSWORD: "Node_introduction"
      ACCEPT_EULA: "Y"